### ISSUE TITLE
Reader classes

### ISSUE THREAD

**Issue by apiszcz** [dstl/Stone-Soup#371] opened 2021-02-05 20:43 UTC
So far I handle the input readers on my own. However I'd like to consider the SS readers. I did not find these features in the documentation. 

1. Do the readers have a tail mode that reads from the end of the file and keeps track of new data as it is appended?
2. Tail mode may require keeping the state of the file so on restarts it can recover and start from the last known recoid.
3. Is it possible to add position based indexing for the CSV streams, no headers just streaming column data?

**Comment by sdhiscocks** [comment] 2021-02-09 10:06
So 3. could be worked around with [current reader](https://stonesoup.readthedocs.io/en/v0.1b3/stonesoup.reader.html#stonesoup.reader.generic.CSVDetectionReader) with `csv_options`, adding [`fieldnames`](https://docs.python.org/3/library/csv.html#csv.DictReader) option.

For example a file like this:
```
2021/02/09 10:00:01,100,200
2021/02/09 10:00:02,101,200
2021/02/09 10:00:03,101,201
2021/02/09 10:00:04,100,202
```
```python
CSVDetectionReader(
    path="my_file.csv",
    state_vector_fields=('x', 'y'),
    time_field='t',
    csv_options={'fieldnames': ('t', 'x', 'y')}
```

For 1. and 2., we'll have to look at creating a tail mode option.

**Comment by apiszcz** [comment] 2021-02-09 12:13
Thanks for the workaround, that is helpful.
I tried a reverse file reader and use pygtail. I will be ready to test the implementation when ready.
Reading the end of a file should be a common use case/pattern.

**Comment by sdhiscocks** [comment] 2021-03-22 08:28
Closing as 3. resolve, and 1. and 2. duplicate of #211

**Closed by sdhiscocks** 2021-03-22 08:28 UTC
Labels: enhancement
