### ISSUE TITLE
metrics division by zero error.

### ISSUE THREAD

**Issue by apiszcz** [dstl/Stone-Soup#312] opened 2020-10-02 11:55 UTC
Testing a random walk transition model with different (position noise diffusion coefficient q) values and the first few values 0.1, 1.0 are good. Using 10.0 I am getting this. Assume there are no tracks or I have  other issues.

```
Traceback (most recent call last):
  File "APP1.py", line 1848, in run
    self.metrics_generate()
  File "APP1.py", line 1785, in metrics_generate
    self.metrics = self.metric_manager.generate_metrics()
  File "lib\site-packages\stonesoup\metricgenerator\manager.py", line 91, in generate_metrics
    metric = generator.compute_metric(self)
  File "lib\site-packages\stonesoup\metricgenerator\tracktotruthmetrics.py", line 45, in compute_metric
    self.A_time_range(manager),
  File "lib\site-packages\stonesoup\metricgenerator\tracktotruthmetrics.py", line 169, in A_time_range
    manager, timestamps)
ZeroDivisionError: division by zero
```

**Comment by sdhiscocks** [comment] 2020-10-06 07:22
This is duplicate of #209 so will close. I'm currently looking at my previous PR #215  again.

**Closed by sdhiscocks** 2020-10-06 07:22 UTC
